name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      # Setup Python
      - name: install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      # Update Pip
      - name: update pip
        run: python -m pip install --upgrade pip
      # Install Requirements
      - name: install requirements
        run: pip install -r requirements.txt
      # Run Tests with Pytest
      - name: test with pytest
        run:
          pip install pytest
          pytest -v