name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    # Environment (TEST, DEV, PROD)
    environment:
      name: testing
    # Environment variables
    env: 
        DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
        DATABASE_PORT: ${{secrets.DATABASE_PORT}}
        DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        DATABASE_NAME: ${{secrets.DATABASE_NAME}}
        DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        ALGORITHM: ${{secrets.ALGORITHM}}
        ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      # Setup Python
      - name: install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      # Update Pip
      - name: update pip
        run: python -m pip install --upgrade pip
      # Install Requirements
      - name: install requirements
        run: pip install -r requirements.txt
      # Run Tests with Pytest
      - name: test with pytest
        run: |
          pip install pytest
          pytest